// app/components/word-relations.tsx
import { Fragment } from "react";
import { Link } from "react-router";

type Props = { values: string[]; label: string };

export const WordRelations = ({ values, label }: Props) => {
  return (
    <dl className="flex items-start gap-4">
      <dt className="text-xl text-grey-400">{label}</dt>
      <dd>
        <ul className="flex flex-wrap items-center gap-2 text-lg font-bold text-accent-200">
          {values.map((value, i) => (
            <Fragment key={`${value + i}}`}>
              <li>
                <Link
                  to={new URL(
                    encodeURI(`https://en.wiktionary.org/wiki/${value}`),
                  ).toString()}
                  className="hocus:underline"
                >
                  {value}
                </Link>
              </li>
            </Fragment>
          ))}
        </ul>
      </dd>
    </dl>
  );
};

// src/lib/components/word-relations.svelte
<script lang="ts">
  import { hasValues } from '$lib/helpers/utils';
  import Link from '$lib/ui/link.svelte';

  type Props = { label: string; words: string[] };

  const { label, words }: Props = $props();
</script>

{#if hasValues(words)}
  <dl class="flex items-start gap-4">
    <dt class="text-grey-400 text-base md:text-xl">{label}</dt>
    <dd>
      <ul
        class={[
          'flex flex-wrap items-center gap-2',
          'text-accent-200 text-lg font-bold md:text-xl'
        ]}
      >
        {#each words as word (word)}
          <li>
            <Link
              href={encodeURI(`https://en.wiktionary.org/wiki/${word}`)}
              class="hocus:underline"
            >
              {word}
            </Link>
          </li>
        {/each}
      </ul>
    </dd>
  </dl>
{/if}
